# Based on: https://github.com/arthurlopes/ctbench/blob/master/FlowTracker/dudect%20examples/aes32/in.xml
functions:
  - rijndaelKeySetupEnc
  # - rijndaelKeySetupDec => cannot unroll loops
  - rijndaelEncrypt
  # - rijndaelDecrypt => not used
cache:
  - --I1=16384;4;1024
  - --D1=16384;4;1024
  - --LL=16384;4;1024
