# Based on: https://github.com/arthurlopes/ctbench/blob/master/FlowTracker/BearSSL/hash/md5/in.xml
functions:
  - br_md5_round
cache:
  - --I1=16384;4;1024
  - --D1=16384;4;1024
  - --LL=16384;4;1024
